name: ci

run-name: test code geometric_lib
on: [push]
  # push:
  #   branches:
  #     - master
  #     - release
  # pull_request:
  #   branches:
  #     - master
  #     - release
  #     - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STUDENT_NAME: "Кочкин Кирилл Алексеевич"
      GROUP_NUMBER: "M3111"

    steps:
      - name: Print Info
        run: |
          echo "ФИО: ${{ env.STUDENT_NAME }}"
          echo "Группа: ${{ env.GROUP_NUMBER }}"
          echo "Ник на Github: ${{ github.actor }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r req

      - name: Run tests
        run: python -m unittest discover

      - name: Check code style
        run: flake8

      - name: Format code (optional)
        run: black .
        if: ${{ failure() }}
